image: docker:latest
services:
  - docker:dind

# variables:
#   DOCKER_DRIVER: overlay
#   SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - test
  - visualize
  - build
  # - review
  # - deploy

# maven-build:
#   image: maven:3-jdk-8
#   stage: build
#   script: "mvn package -B"
#   artifacts:
#     paths:
#       - target/*.jar
test: 
  image: maven:3.6.0-jdk-11-slim
  stage: test
  only: 
    - merge_requests
  script:
    - mvn test
  artifacts: 
    # reports:
    #   cobertura: target/site/cobertura.xml
    paths:
    - target/surefire-reports/TEST-*.xml
    - target/failsafe-reports/TEST-*.xml
    - target/site/jacoco/jacoco.xml

coverage:
  # Must be in a stage later than test-jdk11's stage.
  # The `visualize` stage does not exist by default.
  # Please define it first, or choose an existing stage like `deploy`.
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
    - cat target/site/cobertura.xml
  artifacts:
    reports:
      cobertura: target/site/cobertura.xml

docker-build:
  stage: build
  only: 
    - main
    - merge_requests
  variables: 
    CONTAINER_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  before_script: 
    - docker login $CI_REGISTRY -u $DOCKER_USER -p $DOCKER_PASSWORD 
  script:
    - docker build -t $CONTAINER_NAME -f ./docker-config/app/Dockerfile .
    - docker push $CONTAINER_NAME
  
# k8s-deploy:
#   image: google/cloud-sdk
#   stage: deploy
#   script:
#   - echo "$GOOGLE_KEY" > key.json
#   - gcloud auth activate-service-account --key-file key.json
#   - gcloud config set compute/zone europe-west1-c
#   - gcloud config set project actuator-sample
#   - gcloud config set container/use_client_certificate True
#   - gcloud container clusters get-credentials actuator-sample
#   - kubectl delete secret registry.gitlab.com
#   - kubectl create secret docker-registry registry.gitlab.com --docker-server=https://registry.gitlab.com --docker-username=marcolenzo --docker-password=$REGISTRY_PASSWD --docker-email=lenzo.marco@gmail.com
#   - kubectl apply -f deployment.yml
