# variables:
#   DOCKER_DRIVER: overlay
#   SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - test
  - build
  - production
  - production-proxy
  # - review

test: 
  image: maven:3.6.0-jdk-11-slim
  stage: test
  only: 
    - merge_requests
    - main
  tags:
    - docker-runner-imovel-ideal
  script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
    - awk -F "," '
          {
            instructions += $4 + $5; covered += $5
          }
          END {
            print covered, "/", instructions, "instructions covered";
            printf "%.f%% covered\n", covered / instructions * 100
          }' target/site/jacoco/jacoco.csv
  artifacts: 
    paths: 
        - target/site/jacoco/
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

app-build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  only: 
    - main
    - merge_requests
  tags:
    - docker-runner-imovel-ideal
  variables: 
    CONTAINER_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/app
  before_script: 
    - docker login $CI_REGISTRY -u $DOCKER_USER -p $DOCKER_PASSWORD 
  script:
    - docker build -t $CONTAINER_NAME -f ./docker-config/app/Dockerfile .
    - docker push $CONTAINER_NAME

deploy:
  stage: production
  environment: 
    name: live
    url: http://imovelideal.lvff.me
  only: 
    - main
  tags:
    - imovel-ideal-vm1-shell
  variables: 
    WORKDIR_PATH: /var/www/production
  before_script:
    - docker login $CI_REGISTRY -u $DOCKER_USER -p $DOCKER_PASSWORD
  script: 
    - cp -f $env $WORKDIR_PATH/.env
    - cp -f docker-compose.production.yml $WORKDIR_PATH/docker-compose.yml
    - cp -f $dbpassword $WORKDIR_PATH/.dbpassword
    - cd $WORKDIR_PATH
    - docker-compose pull
    - docker-compose up --scale app=2 --remove-orphans -d
    - docker image prune -f
  after_script:
    - docker logout
    - rm -f -- /var/www/.dbpassword

deploy-traefik:
  stage: production-proxy
  only: 
    - main
  needs: []
  when: manual
  tags:
    - imovel-ideal-vm1-shell
  variables: 
    WORKDIR_PATH: /var/www/traefik
  script:
    - echo "COMPOSE_PROJECT_NAME=imovel-ideal" > $WORKDIR_PATH/.env
    - cp -f traefik-compose.yml $WORKDIR_PATH/docker-compose.yml
    - cd $WORKDIR_PATH
    - docker-compose pull
    - docker-compose up --remove-orphans -d
    - docker image prune -f