version: '3.3'

volumes:
  imovel-ideal:

networks: 
  imovel-ideal-db:
    driver: bridge

  proxy:
    external:
      name: "imovel-ideal_external-proxy"

secrets:    
  dbpassword:
    file: .dbpassword

services:
  app: 
    image: registry.gitlab.com/leonardovff/sprint-boot-devops/app:latest
    restart: always
    labels:
      - "traefik.http.routers.app.rule=Host(`imovelideal.lvff.me`)"
      - "traefik.enable=true"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_INTERNAL_PORT: ${MYSQL_INTERNAL_PORT}
    # ports: 
    #   - "8080:8080"
    networks:
      - imovel-ideal-db
      - proxy
    depends_on:
      - "db"
    secrets:
      - dbpassword

  db:
    image: registry.gitlab.com/leonardovff/sprint-boot-devops/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/dbpassword
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/dbpassword
    secrets:
      - dbpassword
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}"
    networks:
      - imovel-ideal-db
    volumes:
      - imovel-ideal:/var/lib/mysql