version: '3.3'

volumes:
  imovel-ideal:

networks: 
  imovel-ideal-db:
    driver: bridge
  
  imovel-ideal-proxy:
    driver: bridge

secrets:    
  dbpassword:
    file: .dbpassword

services:
  proxy:
    image: registry.gitlab.com/leonardovff/sprint-boot-devops/loadbalance:latest
    restart: always
    ports:
      - "80:81"
    networks:
      - imovel-ideal-proxy
    depends_on:
      - "app1"
      - "app2"

  app1: 
    image: registry.gitlab.com/leonardovff/sprint-boot-devops/app:latest
    restart: always
    labels:
      - "traefik.http.routers.app1.rule=Host(`whoami.docker.localhost`)"
      # - "traefik.http.services.app1.loadBalancer.server.port=8080"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_INTERNAL_PORT: ${MYSQL_INTERNAL_PORT}
    # ports: 
    #   - "9000:8080"
    networks:
      - imovel-ideal-db
      - imovel-ideal-proxy
    depends_on:
      - "db"
    secrets:
      - dbpassword

  app2: 
    image: registry.gitlab.com/leonardovff/sprint-boot-devops/app:latest
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_INTERNAL_PORT: ${MYSQL_INTERNAL_PORT}
    networks:
      - imovel-ideal-db
      - imovel-ideal-proxy
    depends_on:
      - "db"
    secrets:
      - dbpassword

  db:
    image: registry.gitlab.com/leonardovff/sprint-boot-devops/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/dbpassword
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/dbpassword
    secrets:
      - dbpassword
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}"
    networks:
      - imovel-ideal-db
      - imovel-ideal-proxy
    volumes:
      - imovel-ideal:/var/lib/mysql